"""wampdata stamp

Revision ID: a8c29d33b1c8
Revises: d618cc27c6ad
Create Date: 2021-06-04 06:26:09.051094

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a8c29d33b1c8'
down_revision = 'd618cc27c6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wampdata', sa.Column('stamp', sa.Float(), nullable=True))
    op.execute("update wampdata set stamp = (data->'timestamp')::float")
    op.alter_column('wampdata', 'stamp',nullable=False)
    
    op.create_index('ix_wampdata_event_id', 'wampdata', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wampdata', 'stamp')
    # ### end Alembic commands ###
