"""event addons

Revision ID: d618cc27c6ad
Revises: 3ebf1ffd2db2
Create Date: 2021-05-30 08:10:46.797289

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd618cc27c6ad'
down_revision = '3ebf1ffd2db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.String(), nullable=True))
    op.add_column('event', sa.Column('record_stamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'record_stamp')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
