from dataclasses import dataclass
from dataclasses import field


@dataclass
class EventLookup:
    lookup: dict = field(default_factory=dict)

@dataclass
class Manifest:
    car: list[str]
    state: list[str]
    session: list[str]

@dataclass 
class EventInfo:
    name: str
    description: field(init=False,default="")

@dataclass 
class ProviderData:
    """holds data for an event from one data provider"""
    eventKey: str
    """the event key generated by the provider"""
    manifests: Manifest = field(repr=True)
    """manifest info for recording event"""
    info: EventInfo

    dbId: int = field(default=None, repr=True)
    """the id used for the database"""

